# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-01 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_usermessage_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsult',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='手机'),
        ),
    ]
