# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180116_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='images',
            field=models.ImageField(upload_to='image/courses/%Y/%m', verbose_name='封面图'),
        ),
    ]
