# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='images',
            field=models.ImageField(upload_to='courses/%Y/%m', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='resource/%Y/%m', verbose_name='资源文件'),
        ),
    ]
