# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180207_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='课程名'),
        ),
    ]
