# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20180207_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(default='', max_length=100, verbose_name='课程标签'),
        ),
    ]
