# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20180208_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否为广告位'),
        ),
    ]
