# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20180228_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m', verbose_name='封面图'),
        ),
    ]
