# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180116_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='images',
            field=models.ImageField(default='image/default.png', upload_to='image/users/%Y/%m'),
        ),
    ]
