# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-02 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180117_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='images',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='users/%Y/%m'),
        ),
    ]
