# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-23 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180223_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecode',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('update_email', '修改邮箱')], max_length=20, verbose_name='验证码类型'),
        ),
    ]
